import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    labelApproval: "approval",
    labelQuestion: "question",
    labelImages: "images",
    labelHtml: "html",
    labelChart: "chart",
    labelRefresh: "refresh",
    labelSubagent: "subagent",
    labelDelegation: "delegation",
    labelExaSearch: "exa",
    labelMemory: "memory",
    
    argApprovalRequest: "Approval Request",
    argUserQuestion: "User Question",
    argImages: "images",
    argChart: "Chart",
    argHtmlDoc: "HTML document",
    argUiRefresh: "UI refresh",
    
    resWaiting: "waiting...",
    resRendered: "rendered",
    resShared: "shared",
    resRefreshed: "refreshed",
    resCompleted: "completed",
    resExaResults: "results",
    resExaResult: "result",
    resMemories: "memories",
    resMemory: "memory",
    resStored: "stored",
    resForgotten: "forgotten",
    
    bodySubagentConsole: "Subagent Console",
    bodyViewLiveConsole: "View Live Console",
    bodyWorkspaceRefreshed: "Workspace sections refreshed: ",
    bodyDelegationTo: "Delegation to",
    bodySynthesizedOutput: "Synthesized Output",
    bodyShowMore: "Show {n} more",
    bodyNoResults: "No results found",
    bodyNoMemories: "No relevant memories found",
    bodyMemoriesRecalled: "memories recalled",
  },
  es: {
    labelApproval: "aprobación",
    labelQuestion: "pregunta",
    labelImages: "imágenes",
    labelHtml: "html",
    labelChart: "gráfico",
    labelRefresh: "refrescar",
    labelSubagent: "subagente",
    labelDelegation: "delegación",
    labelExaSearch: "exa",
    labelMemory: "memoria",
    
    argApprovalRequest: "Petición de aprobación",
    argUserQuestion: "Pregunta al usuario",
    argImages: "imágenes",
    argChart: "Gráfico",
    argHtmlDoc: "documento HTML",
    argUiRefresh: "refresco de UI",
    
    resWaiting: "esperando...",
    resRendered: "renderizado",
    resShared: "compartido",
    resRefreshed: "refrescado",
    resCompleted: "completado",
    resExaResults: "resultados",
    resExaResult: "resultado",
    resMemories: "memorias",
    resMemory: "memoria",
    resStored: "guardado",
    resForgotten: "eliminado",
    
    bodySubagentConsole: "Subagente Consola",
    bodyViewLiveConsole: "Ver Consola en Vivo",
    bodyWorkspaceRefreshed: "Secciones del espacio de trabajo refrescadas: ",
    bodyDelegationTo: "Delegación a",
    bodySynthesizedOutput: "Output sintetizado",
    bodyShowMore: "Mostrar {n} más",
    bodyNoResults: "No se encontraron resultados",
    bodyNoMemories: "No se encontraron memorias relevantes",
    bodyMemoriesRecalled: "memorias recordadas",
  },
};
