import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    agentDetails: "Agent Details",
    role: "Channel Role",
    replyMode: "Reply Mode",
    targetAgents: "Target Agents",
    skills: "Skills",
    tools: "Available Tools",
    noSkills: "No skills configured",
    noTools: "No tools configured",
    removeAgent: "Remove from Channel",
    removeConfirm: "Are you sure you want to remove this agent from the channel?",
    working: "Currently working...",
    thinking: "Thinking...",
    status: "Status",
    save: "Save",
    cancel: "Cancel",
  },
  es: {
    agentDetails: "Detalles del Agente",
    role: "Rol en el Canal",
    replyMode: "Modo de Respuesta",
    targetAgents: "Agentes Destino",
    skills: "Habilidades",
    tools: "Herramientas Disponibles",
    noSkills: "Sin habilidades configuradas",
    noTools: "Sin herramientas configuradas",
    removeAgent: "Eliminar del Canal",
    removeConfirm: "¿Estás seguro de que deseas eliminar este agente del canal?",
    working: "Trabajando actualmente...",
    thinking: "Pensando...",
    status: "Estado",
    save: "Guardar",
    cancel: "Cancelar",
  },
};
