import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    invalidJsonNegotiation: "Invalid JSON in Negotiation Protocol",
    invalidJsonRubric: "Invalid JSON in Scoring Rubric",
    invalidJsonDelegation: "Invalid JSON in Delegation Pattern",
    updateError: "Failed to update channel settings",
    saving: "Saving...",
    saveSettings: "Save Settings",
    tabGeneral: "General",
    tabNegotiation: "Negotiation & Rules",
    tabPolicy: "Policy",
    policyLoading: "Loading effective policy…",
    policyVersion: "Policy version",
    policyChecksum: "Prompt checksum",
    policyHardRules: "Enforced runtime rules",
    policyDiagnostics: "Policy diagnostics",
    enableNegotiation: "Enable Negotiation Protocol",
    agreementPattern: "Agreement Pattern",
    maxRounds: "Max Negotiation Rounds",
    arbiterAgent: "Arbiter Agent",
    noArbiter: "No Arbiter (Horizontal System)",
    rejectionPattern: "Rejection Pattern (Optional)",
    liveActivity: "Live Negotiation Activity",
    activePairs: "Active Pairs",
    agreements: "Agreements",
    divergences: "Divergences (Escalated)",
    arbitrations: "Arbitrations",
    activationRate: "Protocol Activation Rate",
    streamingRenderMode: "Message Rendering Mode",
    renderModeLive: "Live Streaming (character by character)",
    renderModeComplete: "Show on Complete (hides partial text)",
  },
  es: {
    tabPolicy: "Política",
    policyLoading: "Cargando política efectiva…",
    policyVersion: "Versión de política",
    policyChecksum: "Checksum del prompt",
    policyHardRules: "Reglas aplicadas en ejecución",
    policyDiagnostics: "Diagnósticos de política",
    invalidJsonNegotiation: "JSON inválido en Protocolo de Negociación",
    invalidJsonRubric: "JSON inválido en Rúbrica de Evaluación",
    invalidJsonDelegation: "JSON inválido en Patrón de Delegación",
    updateError: "Error al actualizar la configuración del canal",
    saving: "Guardando...",
    saveSettings: "Guardar Ajustes",
    tabGeneral: "General",
    tabNegotiation: "Negociación y Reglas",
    enableNegotiation: "Habilitar Protocolo de Negociación",
    agreementPattern: "Patrón de Acuerdo",
    maxRounds: "Rondas Máximas de Negociación",
    arbiterAgent: "Agente Árbitro",
    noArbiter: "Sin Árbitro (Sistema Horizontal)",
    rejectionPattern: "Patrón de Rechazo (Opcional)",
    liveActivity: "Actividad de Negociación en Vivo",
    activePairs: "Pares Activos",
    agreements: "Acuerdos",
    divergences: "Divergencias (Escaladas)",
    arbitrations: "Arbitrajes",
    activationRate: "Tasa de Activación del Protocolo",
    streamingRenderMode: "Modo de Renderizado de Mensajes",
    renderModeLive: "Streaming en Vivo (carácter por carácter)",
    renderModeComplete: "Mostrar al Completar (oculta texto parcial)",
  },
};
