import { piSessionManager } from "../pi/session-manager";

export class LabJudge {
  static async evaluateRuns(
    username: string,
    taskPrompt: string,
    criteria: string[],
    outputs: {
      single: string;
      multiNoLeader: string;
      multiWithLeader: string;
    }
  ): Promise<{
    single: { scores: Record<string, number>; globalScore: number; reasoning: string };
    multiNoLeader: { scores: Record<string, number>; globalScore: number; reasoning: string };
    multiWithLeader: { scores: Record<string, number>; globalScore: number; reasoning: string };
  }> {
    const sessionId = `judge_${crypto.randomUUID()}`;
    const session = await piSessionManager.getOrCreateSession(username, sessionId);

    const judgePrompt = `
You are an expert AI evaluator. Evaluate the following three different outputs produced for the same task.
Each output was generated by a different agent configuration (Single Agent, Multi-Agent No Leader, and Multi-Agent With Leader).
Your assessment must be objective and evaluate the outputs against the listed criteria.

Task Prompt:
"${taskPrompt}"

Criteria to score (0-100 for each):
${JSON.stringify(criteria)}

---
Output A:
${outputs.single || "(No output produced)"}
---
Output B:
${outputs.multiNoLeader || "(No output produced)"}
---
Output C:
${outputs.multiWithLeader || "(No output produced)"}
---

For each output, assign a score (0 to 100) for each criteria, a global quality score (0 to 100), and a concise reasoning text (max 2 sentences).

Output ONLY a JSON object matching this structure (no markdown boxes, code fences or conversational text):
{
  "single": {
    "scores": { "Criterion1": 85, "Criterion2": 90 },
    "globalScore": 87,
    "reasoning": "Output A is clean and simple but lacks deeper risk analysis."
  },
  "multiNoLeader": {
    "scores": { "Criterion1": 90, "Criterion2": 95 },
    "globalScore": 92,
    "reasoning": "Output B covers a wider range of edge cases and security measures."
  },
  "multiWithLeader": {
    "scores": { "Criterion1": 95, "Criterion2": 95 },
    "globalScore": 95,
    "reasoning": "Output C is highly detailed, well-structured, and has a professional commercial tone."
  }
}
`;

    try {
      await session.prompt(judgePrompt);
      const msgs = session.messages;
      const lastMsg = [...msgs].reverse().find((m) => m.role === "assistant");
      let rawJson = "";
      if (lastMsg) {
        if (typeof lastMsg.content === "string") rawJson = lastMsg.content;
        else if (Array.isArray(lastMsg.content)) {
          rawJson = lastMsg.content.map((c: any) => c.text || "").join("\n");
        }
      }

      rawJson = rawJson.trim();
      if (rawJson.startsWith("```")) {
        rawJson = rawJson.replace(/^```[a-zA-Z-]*\n/, "").replace(/\n```$/, "");
      }

      const parsed = JSON.parse(rawJson);
      return {
        single: parsed.single || { scores: {}, globalScore: 70, reasoning: "No assessment returned." },
        multiNoLeader: parsed.multiNoLeader || { scores: {}, globalScore: 75, reasoning: "No assessment returned." },
        multiWithLeader: parsed.multiWithLeader || { scores: {}, globalScore: 80, reasoning: "No assessment returned." },
      };
    } catch (e) {
      console.error("[LabJudge] Failed to evaluate runs:", e);
      return {
        single: { scores: {}, globalScore: 70, reasoning: "Evaluation failed due to parsing error." },
        multiNoLeader: { scores: {}, globalScore: 75, reasoning: "Evaluation failed due to parsing error." },
        multiWithLeader: { scores: {}, globalScore: 80, reasoning: "Evaluation failed due to parsing error." },
      };
    } finally {
      await piSessionManager.destroySession(username, sessionId);
    }
  }
}
