import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    deleting: "Deleting...",
    delete: "Delete",
    chat: "Chat",
    history: "History",
    edit: "Edit",
    pageTitle: "Agents",
    pageSubtitle: "Programmatic agents — independent AI workers with isolated workspaces",
    refresh: "Refresh",
    registerAgent: "Register Agent",
    emptyTitle: "No agents running",
    emptyDescription: "Register your first agent to get started",
    registerAgentBtn: "Register Agent",
    editAgent: "Edit Agent",
    registerAgentTitle: "Register Agent",
    editAgentDesc: "Modify the agent configuration",
    registerAgentDesc: "Define a new programmatic agent",
    idField: "ID *",
    nameField: "Name *",
    roleField: "Role *",
    portField: "Port (optional)",
    modelField: "Model (optional)",
    skillsField: "Skills (comma-separated)",
    systemPromptField: "System Prompt *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "anthropic/claude-3-5-sonnet-20241022",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "You are an expert web developer specializing in React and TypeScript...",
    saving: "Saving...",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    execTitle: "Execution History",
    execSubtitle: "Analyze performance and logs of delegated tasks",
    noExecutions: "No executions recorded.",
    loadExecError: "Failed to load executions",
    selectExecHint: "Select an execution to view details",
    execDuration: "Execution Duration",
    execStatus: "Status",
    seconds: " seconds",
    success: "Successful",
    errors: " Error(s)",
    errorsFound: "Errors Found",
    executedTools: "Executed Tools",
    noTools: "No tools were executed in this task.",
    running: "running",
    sessionMessages: "Session Messages",
    prompt: "Prompt",
    arguments: "Arguments",
    result: "Result",
    saveError: "Failed to save agent",
    idPatternTitle: "lowercase letters, numbers, and dashes only",
    deleteConfirm_1: 'Are you sure you want to delete agent "',
    deleteConfirm_2: '"? This will stop its server and permanently delete all its associated chat sessions.',
  },
  es: {
    deleting: "Eliminando...",
    delete: "Eliminar",
    chat: "Chat",
    history: "Historial",
    edit: "Editar",
    pageTitle: "Agentes",
    pageSubtitle: "Agentes programaticos — trabajadores IA independientes con workspaces aislados",
    refresh: "Actualizar",
    registerAgent: "Registrar Agente",
    emptyTitle: "No hay agentes activos",
    emptyDescription: "Registra tu primer agente para empezar",
    registerAgentBtn: "Registrar Agente",
    editAgent: "Editar Agente",
    registerAgentTitle: "Registrar Agente",
    editAgentDesc: "Modifica la configuracion del agente",
    registerAgentDesc: "Define un nuevo agente programatico",
    idField: "ID *",
    nameField: "Nombre *",
    roleField: "Rol *",
    portField: "Puerto (opcional)",
    modelField: "Modelo (opcional)",
    skillsField: "Skills (separadas por coma)",
    systemPromptField: "Prompt de Sistema *",
    idPlaceholder: "web-builder",
    namePlaceholder: "Web Builder",
    rolePlaceholder: "web-builder",
    portPlaceholder: "4200",
    modelPlaceholder: "anthropic/claude-3-5-sonnet-20241022",
    skillsPlaceholder: "github-deploy, cloudflare-deploy",
    systemPromptPlaceholder: "Eres un desarrollador web experto especializado en React y TypeScript...",
    saving: "Guardando...",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    execTitle: "Historial de Ejecuciones",
    execSubtitle: "Analiza el rendimiento y logs de tareas delegadas",
    noExecutions: "Sin ejecuciones registradas.",
    loadExecError: "Error al cargar ejecuciones",
    selectExecHint: "Selecciona una ejecucion para ver el detalle",
    execDuration: "Duracion de Ejecucion",
    execStatus: "Estado",
    seconds: " segundos",
    success: "Exitosa",
    errors: " Error(es)",
    errorsFound: "Errores Encontrados",
    executedTools: "Herramientas Ejecutadas",
    noTools: "No se ejecutaron herramientas en esta tarea.",
    running: "corriendo",
    sessionMessages: "Mensajes de Sesion",
    prompt: "Prompt",
    arguments: "Argumentos",
    result: "Resultado",
    saveError: "Error al guardar el agente",
    idPatternTitle: "solo minusculas, numeros y guiones",
    deleteConfirm_1: "¿Estas seguro de que quieres eliminar al agente \"",
    deleteConfirm_2: "\"? Esto detendra su servidor y eliminara todas sus sesiones de chat asociadas de manera permanente.",
  },
};
