import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    createTitle: "Create Channel",
    createSubtitle: "Start a new multi-agent conversation space",
    channelNameLabel: "Channel Name *",
    channelNamePlaceholder: "e.g. project-planning",
    descriptionLabel: "Description (optional)",
    descriptionPlaceholder: "Discuss and coordinate feature implementations",
    cancel: "Cancel",
    creating: "Creating...",
    createChannel: "Create Channel",
    createError: "Failed to create channel",
    pageTitle: "Channels",
    pageSubtitle: "Multi-agent group channels for collaborative agent execution",
    refresh: "Refresh",
    emptyTitle: "No channels created",
    emptyDescription: "Create a channel to bring multiple agents together",
    emptyButton: "Create Channel",
  },
  es: {
    createTitle: "Crear Canal",
    createSubtitle: "Inicia un nuevo espacio de conversacion multi-agente",
    channelNameLabel: "Nombre del Canal *",
    channelNamePlaceholder: "ej. planificacion-proyecto",
    descriptionLabel: "Descripcion (opcional)",
    descriptionPlaceholder: "Discutir y coordinar implementaciones de funcionalidades",
    cancel: "Cancelar",
    creating: "Creando...",
    createChannel: "Crear Canal",
    createError: "Error al crear el canal",
    pageTitle: "Canales",
    pageSubtitle: "Canales de grupo multi-agente para ejecucion colaborativa",
    refresh: "Actualizar",
    emptyTitle: "No hay canales creados",
    emptyDescription: "Crea un canal para reunir multiples agentes",
    emptyButton: "Crear Canal",
  },
};
