import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    channelNotFound: "Channel not found",
    backToChannels: "Back to Channels",
    chat: "Chat",
    orgChart: "Org Chart",
    tabChat: "Chat",
    tabAnalytics: "Analytics",
    tabSwimlanes: "Swimlanes",
    kpiTotalSessions: "Total Sessions",
    kpiVetoRate: "Veto Rate",
    kpiArbitrations: "Arbitrations",
    kpiAvgResponse: "Avg Response Time",
    chartTurnsTitle: "Agent Turns Distribution",
    loadingAnalytics: "Loading channel analytics...",
    noAnalytics: "No analytics data available for this channel",
    noMessagesForSwimlane: "Send messages in the chat to view the agent arbitration timeline.",
  },
  es: {
    channelNotFound: "Canal no encontrado",
    backToChannels: "Volver a Canales",
    chat: "Chat",
    orgChart: "Organigrama",
    tabChat: "Chat",
    tabAnalytics: "Analíticas",
    tabSwimlanes: "Líneas de Agentes",
    kpiTotalSessions: "Sesiones Totales",
    kpiVetoRate: "Tasa de Veto",
    kpiArbitrations: "Arbitrajes",
    kpiAvgResponse: "Tiempo Medio de Respuesta",
    chartTurnsTitle: "Distribución de Turnos por Agente",
    loadingAnalytics: "Cargando analíticas del canal...",
    noAnalytics: "No hay analíticas disponibles para este canal",
    noMessagesForSwimlane: "Envia mensajes en el chat para ver la línea de tiempo de arbitraje entre agentes.",
  },
};
