import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    tabSessions: "Sessions",
    tabLogs: "Logs",
    filterAll: "All",
    filterSession: "Session",
    filterChannel: "Channel",
    statusActive: "Active now",
    statusMomentsAgo: "Just now",
    statusMinutesAgo: "minute",
    statusHoursAgo: "hour",
    statusNoActivity: "No activity recorded",
    labelSourceSession: "Session",
    labelSourceChannel: "Channel",
    labelUser: "User:",
    labelResponse: "Response:",
    labelWriting: "Writing:",
    labelThinking: "Thinking:",
    labelToolStart: "Tool Start:",
    labelToolEnd: "Tool End:",
    toolSuccess: "success",
    toolError: "error",
    labelError: "Error",
    labelResultTruncated: "(result truncated)",
    scrollToTop: "Scroll to Top",
    autoScroll: "Auto-scroll",
    clear: "Clear",
    loadMore: "Load older logs",
  },
  es: {
    tabSessions: "Sesiones Activas",
    tabLogs: "Consola de Logs",
    filterAll: "Todas",
    filterSession: "Sesion",
    filterChannel: "Canal",
    statusActive: "Activa ahora",
    statusMomentsAgo: "Hace unos instantes",
    statusMinutesAgo: "minuto",
    statusHoursAgo: "hora",
    statusNoActivity: "Sin actividad registrada",
    labelSourceSession: "Sesion",
    labelSourceChannel: "Canal",
    labelUser: "Usuario:",
    labelResponse: "Respuesta:",
    labelWriting: "Escribiendo:",
    labelThinking: "Pensando:",
    labelToolStart: "Inicio de Herramienta:",
    labelToolEnd: "Fin de Herramienta:",
    toolSuccess: "exitoso",
    toolError: "error",
    labelError: "Error",
    labelResultTruncated: "(resultado truncado)",
    scrollToTop: "Ir al inicio",
    autoScroll: "Auto-scroll",
    clear: "Limpiar",
    loadMore: "Cargar logs anteriores",
  },
};
