import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    pluginsTitle: "Add-ons & Plugins",
    pluginsSubtitle: "Extend the capabilities of your agents with persistent memory and advanced neural search integrations.",
    cardEngramTitle: "Persistent Agent Memory (Engram)",
    cardEngramDesc: "Provides long-term semantic, episodic, and procedural memory using local SQLite and neural embeddings (ONNX). Stored 100% locally.",
    cardExaTitle: "Exa Neural Web Search",
    cardExaDesc: "Enables agents to perform grounded web search with neural embeddings, excerpt extraction, and structured synthesis.",
    statusEnabled: "Active",
    statusDisabled: "Inactive",
    statusConfigured: "Configured",
    statusMissingKey: "Missing API Key",
    enablePlugin: "Enable persistent memory",
    autoStoreInteractions: "Auto-store interactions (episodic memory)",
    localEmbeddings: "Use local neural embeddings (requires ~23MB ONNX download)",
    localOnlyNotice: "Memory is isolated per agent/channel. No external API calls are made.",
    missingKeyWarning: "This plugin requires EXA_API_KEY to be configured in Settings.",
    configureKeyLink: "Go to Settings > Env Vars to configure",
    globalActivation: "Enable by default for new sessions",
    saveSuccess: "Plugins settings updated successfully.",
    fetchError: "Failed to load plugins configuration.",
    saveError: "Failed to save plugins configuration.",
  },
  es: {
    pluginsTitle: "Add-ons y Plugins",
    pluginsSubtitle: "Extiende las capacidades de tus agentes con memoria persistente e integraciones avanzadas de búsqueda neural.",
    cardEngramTitle: "Memoria Persistente para Agentes (Engram)",
    cardEngramDesc: "Provee memoria semántica, episódica y procedural a largo plazo mediante SQLite local y embeddings neuronales (ONNX). Guardado 100% local.",
    cardExaTitle: "Búsqueda Web Neural (Exa)",
    cardExaDesc: "Permite a los agentes realizar búsquedas web basadas en contexto con embeddings neuronales, extracción de citas y síntesis estructurada.",
    statusEnabled: "Activo",
    statusDisabled: "Inactivo",
    statusConfigured: "Configurado",
    statusMissingKey: "Falta API Key",
    enablePlugin: "Habilitar memoria persistente",
    autoStoreInteractions: "Auto-guardar interacciones (memoria episódica)",
    localEmbeddings: "Usar embeddings locales (requiere descargar ~23MB de ONNX)",
    localOnlyNotice: "La memoria está aislada por agente/canal. No se realizan llamadas a APIs externas.",
    missingKeyWarning: "Este plugin requiere configurar EXA_API_KEY en Ajustes.",
    configureKeyLink: "Ir a Ajustes > Vars de Entorno para configurar",
    globalActivation: "Habilitar por defecto en nuevas sesiones",
    saveSuccess: "Ajustes de plugins actualizados con éxito.",
    fetchError: "Error al cargar la configuración de plugins.",
    saveError: "Error al guardar la configuración de plugins.",
  },
};
