import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Projects",
    subtitle: "Initialize an empty project or clone an existing Git repository to work with the agent.",
    workspaceGlobal: "Global Workspace",
    newProject: "+ New Project",
    loading: "Loading repositories...",
    id: "ID:",
    lastModified: "Last modified:",
    open: "Open",
    renameTooltip: "Rename Project",
    deleteTooltip: "Delete Project",
    emptyTitle: "No projects yet",
    emptyDescription: "Create or clone a repository to start working with the agent.",
    emptyButton: "Create project",
    createModalTitle: "New Project / Repository",
    projectNameLabel: "Project Name",
    projectNamePlaceholder: "e.g. my-web-app",
    cloneUrlLabel: "Git Clone URL (Optional)",
    cloneUrlPlaceholder: "e.g. https://github.com/user/repo.git",
    avatarUrlLabel: "Avatar/Image URL (Optional)",
    avatarUrlPlaceholder: "e.g. https://example.com/avatar.png",
    cancel: "Cancel",
    creating: "Creating...",
    createProject: "Create Project",
    renameModalTitle: "Rename Project",
    newNameLabel: "New Project Name",
    save: "Save",
    deleteModalTitle: "Delete Project",
    deleteDescription: "This action is destructive. It will permanently delete the code folder, uploaded files, and all associated chat sessions.",
    confirmLabel: "Write {name} to confirm:",
    projectNamePlaceholderDelete: "Project name",
    deleting: "Deleting...",
    deleteAnyway: "Delete anyway",
    fetchError: "Failed to fetch repositories",
    loadError: "Failed to load projects",
    renameError: "Failed to rename project",
    deleteError: "Failed to delete project",
    createError: "Failed to create project",
    infoModalTitle: "Project Details",
    cloneUrlLabelEditable: "Git Clone URL",
    createdAtLabel: "Created At",
    diskPathLabel: "Disk Path",
    copyId: "Copy ID",
    copied: "Copied!",
    saveChanges: "Save Changes",
    noValue: "None",
    saving: "Saving...",
  },
  es: {
    title: "Proyectos",
    subtitle: "Inicializa un proyecto vacio o clona uno existente de Git para trabajar con el agente.",
    workspaceGlobal: "Workspace Global",
    newProject: "+ Nuevo Proyecto",
    loading: "Cargando repositorios...",
    id: "ID:",
    lastModified: "Ultima modificacion:",
    open: "Abrir",
    renameTooltip: "Renombrar Proyecto",
    deleteTooltip: "Eliminar Proyecto",
    emptyTitle: "No hay proyectos",
    emptyDescription: "Crea o clona un repositorio para empezar a trabajar con el agente.",
    emptyButton: "Crear proyecto",
    createModalTitle: "Nuevo Proyecto / Repositorio",
    projectNameLabel: "Nombre del Proyecto",
    projectNamePlaceholder: "ej. mi-app-web",
    cloneUrlLabel: "URL de Clonacion Git (Opcional)",
    cloneUrlPlaceholder: "ej. https://github.com/usuario/repo.git",
    avatarUrlLabel: "URL del Avatar/Imagen (Opcional)",
    avatarUrlPlaceholder: "ej. https://ejemplo.com/avatar.png",
    cancel: "Cancelar",
    creating: "Creando...",
    createProject: "Crear Proyecto",
    renameModalTitle: "Renombrar Proyecto",
    newNameLabel: "Nuevo Nombre del Proyecto",
    save: "Guardar",
    deleteModalTitle: "Eliminar Proyecto",
    deleteDescription: "Esta accion es destructiva. Se borrara la carpeta de codigo, los archivos subidos y todas las sesiones de chat asociadas.",
    confirmLabel: "Escribi {name} para confirmar:",
    projectNamePlaceholderDelete: "Nombre del proyecto",
    deleting: "Eliminando...",
    deleteAnyway: "Eliminar de todos modos",
    fetchError: "Failed to fetch repositories",
    loadError: "Failed to load projects",
    renameError: "Failed to rename project",
    deleteError: "Failed to delete project",
    createError: "Failed to create project",
    infoModalTitle: "Detalles del Proyecto",
    cloneUrlLabelEditable: "URL de Clonacion Git",
    createdAtLabel: "Creado el",
    diskPathLabel: "Ruta en Disco",
    copyId: "Copiar ID",
    copied: "Copiado!",
    saveChanges: "Guardar Cambios",
    noValue: "Ninguno",
    saving: "Guardando...",
  },
};
