import { useCallback, useEffect, useState } from "react";
import type { Team, TeamEvent, TeamExecution } from "shared";
import { apiFetch } from "@/lib/api";
import { wsClient } from "@/lib/ws-client";

export function TeamDetailPage({ teamId, onNavigate }: { teamId: string; onNavigate: (path: string) => void }) {
  const [team, setTeam] = useState<Team | null>(null);
  const [execution, setExecution] = useState<TeamExecution | null>(null);
  const [events, setEvents] = useState<TeamEvent[]>([]);
  const [task, setTask] = useState("");
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { const response = await apiFetch(`/api/teams/${teamId}`); if (!response.ok) { setError("Team not found"); return; } setTeam(await response.json() as Team); }, [teamId]);
  const load = useCallback(async (id: string) => { const [executionResponse, eventsResponse] = await Promise.all([apiFetch(`/api/teams/${teamId}/executions/${id}`), apiFetch(`/api/teams/${teamId}/executions/${id}/events?limit=1000`)]); if (executionResponse.ok) setExecution((await executionResponse.json() as { execution: TeamExecution }).execution); if (eventsResponse.ok) setEvents((await eventsResponse.json() as { events: TeamEvent[] }).events); }, [teamId]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { void apiFetch(`/api/teams/${teamId}/executions`).then(async (response) => {
    if (!response.ok) return;
    const data = await response.json() as { executions: TeamExecution[] };
    if (data.executions[0]) await load(data.executions[0].id);
  }); }, [teamId, load]);
  useEffect(() => wsClient.subscribe("team_execution_event", (raw) => { const data = raw as { teamId: string; executionId: string; event: TeamEvent }; if (data.teamId !== teamId) return; setEvents((current) => current.some((event) => event.id === data.event.id) ? current : [...current, data.event]); void load(data.executionId); }), [teamId, load]);
  const submit = async () => { if (!task.trim()) return; const response = await apiFetch(`/api/teams/${teamId}/executions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ task, requestId: crypto.randomUUID() }) }); if (!response.ok) { const data = await response.json().catch(() => ({ error: "Unable to start task" })) as { error?: string }; setError(data.error ?? "Unable to start task"); return; } const data = await response.json() as { executionId?: string }; if (data.executionId) { setEvents([]); await load(data.executionId); } setTask(""); };
  const cancel = async () => { if (execution) await apiFetch(`/api/teams/${teamId}/executions/${execution.id}/cancel`, { method: "POST" }); };
  if (!team) return <div className="h-full p-6 text-sm text-muted-foreground">{error || "Loading team…"}</div>;
  const active = execution && ["queued", "planning", "working", "synthesizing"].includes(execution.status);
  return <div className="h-full overflow-y-auto bg-background p-4 sm:p-6"><div className="mx-auto max-w-4xl"><button onClick={() => onNavigate("/teams")} className="mb-4 text-sm text-muted-foreground hover:text-foreground">← Teams</button><div className="border-b border-border pb-5"><h1 className="text-xl font-semibold text-foreground">{team.name}</h1><p className="mt-1 text-sm text-muted-foreground">{team.description || "Reliable multi-agent delivery."}</p><div className="mt-4 flex flex-wrap gap-2">{team.members.map((member) => <span key={member.agentId} className="rounded-md bg-surface px-2 py-1 text-xs text-muted-foreground">{member.agentId} · {member.role}</span>)}</div></div><section className="py-5"><h2 className="text-sm font-semibold text-foreground">{execution ? execution.status.replace(/_/g, " ") : "Ready"}</h2>{execution && <div className="mt-3 rounded-xl border border-border bg-surface p-4"><p className="text-sm text-foreground">{execution.task}</p>{execution.finalOutput && <div className="mt-4 border-t border-border pt-4"><p className="text-xs font-medium uppercase tracking-wide text-accent">Final delivery</p><pre className="mt-2 whitespace-pre-wrap font-sans text-sm text-foreground">{execution.finalOutput}</pre></div>}</div>}<div className="mt-3 space-y-2">{events.map((event) => <div key={event.id} className="rounded-lg border border-border/70 bg-surface px-3 py-2 text-sm"><span className="font-medium text-foreground">{event.agentId || "Team"}</span><span className="ml-2 text-muted-foreground">{event.type.replace(/_/g, " ")}</span>{typeof event.payload.output === "string" && <p className="mt-1 whitespace-pre-wrap text-muted-foreground">{event.payload.output}</p>}</div>)}</div></section><section className="sticky bottom-0 border-t border-border bg-background py-4"><div className="flex gap-2"><textarea disabled={Boolean(active)} value={task} onChange={(event) => setTask(event.target.value)} placeholder={active ? "A task is already running" : "Describe the task for this team"} className="min-h-20 flex-1 rounded-lg border border-border bg-surface p-3 text-sm text-foreground"/><div className="flex flex-col gap-2"><button disabled={Boolean(active) || !task.trim()} onClick={() => void submit()} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-background disabled:opacity-50">Run task</button>{active && <button onClick={() => void cancel()} className="rounded-lg border border-destructive/40 px-4 py-2 text-sm text-destructive">Cancel</button>}</div></div>{error && <p className="mt-2 text-sm text-destructive">{error}</p>}</section></div></div>;
}
