import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    title: "Team Settings",
    tabGeneral: "General",
    tabNegotiation: "Negotiation & Arbitration",
    name: "Team Name",
    description: "Description",
    maxRounds: "Max Debate Rounds (MAX_ROUNDS)",
    showThinking: "Show Thinking (Reasoning tokens)",
    showTools: "Show Tool Calls",
    negotiationEnabled: "Enable Auto-Negotiation & Arbitration",
    agreementPattern: "Agreement RegExp (Consensus Trigger)",
    rejectPattern: "Rejection RegExp (Veto Trigger)",
    arbiterAgentId: "Arbitrage Agent (Arbiter)",
    none: "None / Disabled",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    updateError: "Failed to update team settings",
    teamType: "Team Type",
    teamTypeImmutable: "The team type is fixed after creation.",
    negotiationDesc: "Negotiation (Debate): Agents debate in parallel; the leader arbitrates if there is a deadlock.",
    orchestrationDesc: "Orchestration (Leader-Specialist): The leader coordinates work and delegates specific tasks to members.",
  },
  es: {
    title: "Ajustes del Equipo",
    tabGeneral: "General",
    tabNegotiation: "Negociación y Arbitraje",
    name: "Nombre del Equipo",
    description: "Descripción",
    maxRounds: "Límite de Rondas de Debate (MAX_ROUNDS)",
    showThinking: "Mostrar Pensamiento (Reasoning tokens)",
    showTools: "Mostrar Ejecución de Herramientas",
    negotiationEnabled: "Activar Auto-Negociación y Arbitraje",
    agreementPattern: "Expresión Regular de Acuerdo (Consenso)",
    rejectPattern: "Expresión Regular de Rechazo (Veto)",
    arbiterAgentId: "Agente de Arbitraje (Árbitro)",
    none: "Ninguno / Desactivado",
    cancel: "Cancelar",
    save: "Guardar",
    saving: "Guardando...",
    updateError: "Error al actualizar ajustes del equipo",
    teamType: "Tipo de Equipo",
    teamTypeImmutable: "El tipo de equipo queda fijado al crearlo.",
    negotiationDesc: "Negociación (Debate): Los agentes debaten en paralelo; el líder arbitra si hay un bloqueo.",
    orchestrationDesc: "Orquestación (Líder-Especialista): El líder coordina el trabajo y delega tareas específicas a los miembros.",
  },
};
