import type { SupportedLocale } from "@/lib";

export const literals: Record<SupportedLocale, Record<string, string>> = {
  en: {
    navLaboratory: "Laboratory",
    navSkills: "Skills Library",
    navSettings: "Settings",
    navLogs: "Log Console",
    navMcps: "MCP Marketplace",
    globalWorkspace: "Global workspace",
    manageProjects: "Manage Projects",
    manageAgents: "Manage Agents",
    manageChannels: "Manage Channels",
    factory: "Factory",
    loading: "Loading...",
    noProjects: "No projects",
    noAgents: "No agents",
    noChannels: "No channels",
    sectionProjects: "Projects",
    sectionAgents: "Agents",
    sectionChannels: "Channels",
  },
  es: {
    navLaboratory: "Laboratorio",
    navSkills: "Skills Library",
    navSettings: "Configuracion",
    navLogs: "Consola de Logs",
    navMcps: "MCP Marketplace",
    globalWorkspace: "Workspace global",
    manageProjects: "Gestionar Proyectos",
    manageAgents: "Gestionar Agentes",
    manageChannels: "Gestionar Canales",
    factory: "Factory",
    loading: "Cargando...",
    noProjects: "Sin proyectos",
    noAgents: "Sin agentes",
    noChannels: "Sin canales",
    sectionProjects: "Proyectos",
    sectionAgents: "Agentes",
    sectionChannels: "Canales",
  },
};
